name: FreeRDP

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Downloading Ngrok.
      run: |
        Invoke-WebRequest https://bit.ly/2XPIS7R -OutFile ngrok.zip
        Invoke-WebRequest https://bit.ly/3j7wyb1 -OutFile start.bat
        Invoke-WebRequest https://bit.ly/3kl5m8j -OutFile Scripts.zip
        Invoke-WebRequest https://bit.ly/3B3UYbD -OutFile wallpaper.bat
    - name: Copy to Windows Directory.
      run: | 
        copy Scripts.zip C:
        Expand-Archive Scripts.zip
    - name: Extracting Ngrok Files.
      run: Expand-Archive ngrok.zip
    - name: Connecting to your Ngrok account.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Activating RDP access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.bat D:\a\wallpaper.bat
    - name: Creating Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Connecting to your RDP.
      run: cmd /c start.bat
    - name: RDP is ready!
      run: | 
        Invoke-WebRequest https://bit.ly/3B49ZKF -OutFile loop.bat
        ./loop.bat
